#!/usr/bin/env python

import sys
import math

import rospy
import tf2_ros 
import tf2_geometry_msgs
from crazyflie_driver.msg import Hover
from aruco_msgs.msg import MarkerArray

pose = Hover()

def hover_callback(data):
    global pose
    pose = data
    print(pose)


def publish_cmd(pose_to_pub):
    global pose
    pub_cmd.publish(pose_to_pub)
    pose = Hover()
    pose.header.stamp = rospy.Time.now()
    pose.vx = 0
    pose.vy = 0
    pose.yawrate = 0
    pose.zDistance = 0.4




rospy.init_node('HOVER')
rospy.Subscriber("HOVER", Hover, hover_callback)
pub_cmd  = rospy.Publisher('/cf1/cmd_hover', Hover, queue_size=2)



def main():

    rate = rospy.Rate(10)  # Hz
    while not rospy.is_shutdown():
        publish_cmd(pose)
        rate.sleep()



if __name__ == "__main__":
    main()