#!/usr/bin/env python

import sys
import math
import readchar

import rospy
import tf2_ros 
import tf2_geometry_msgs
from crazyflie_driver.msg import Hover
from aruco_msgs.msg import MarkerArray


def publish_cmd(pose_to_pub):
    pub_cmd.publish(pose_to_pub)



rospy.init_node('hoverKeyboard')
pub_cmd  = rospy.Publisher('HOVER', Hover, queue_size=2)



def main():
    print("Starting...")
    while True:
        pose = Hover()
        pose.header.stamp = rospy.Time.now()
        pose.vx = 0
        pose.vy = 0
        pose.yawrate = 0
        pose.zDistance = 0.4

        key = readchar.readkey()
        key = key.lower()

        if key == 'c': # QUIT
            print("QUITING.")
            break

        elif key == 'w': # FORWARD
            pose.vx = 0.5

        elif key == 'd': # RIGHT
            pose.vy = 0.5

        elif key == 's': # BACKWARD
            pose.vx = -0.5

        elif key == 'a': # LEFT
            pose.vy = -0.5

        elif key == 'e': # TURN RIGHT
            pose.yawrate = 30

        elif key == 'q': # TURN LEFT
            pose.yawrate = -30
       
        publish_cmd(pose)
    print("...Quiting")


if __name__ == "__main__":
    main()