// Generated by gencpp from file crazyflie_gazebo/AddCrazyflie.msg
// DO NOT EDIT!


#ifndef CRAZYFLIE_GAZEBO_MESSAGE_ADDCRAZYFLIE_H
#define CRAZYFLIE_GAZEBO_MESSAGE_ADDCRAZYFLIE_H

#include <ros/service_traits.h>


#include <crazyflie_gazebo/AddCrazyflieRequest.h>
#include <crazyflie_gazebo/AddCrazyflieResponse.h>


namespace crazyflie_gazebo
{

struct AddCrazyflie
{

typedef AddCrazyflieRequest Request;
typedef AddCrazyflieResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddCrazyflie
} // namespace crazyflie_gazebo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::crazyflie_gazebo::AddCrazyflie > {
  static const char* value()
  {
    return "5b766bccbd53020b32ac296756de42f0";
  }

  static const char* value(const ::crazyflie_gazebo::AddCrazyflie&) { return value(); }
};

template<>
struct DataType< ::crazyflie_gazebo::AddCrazyflie > {
  static const char* value()
  {
    return "crazyflie_gazebo/AddCrazyflie";
  }

  static const char* value(const ::crazyflie_gazebo::AddCrazyflie&) { return value(); }
};


// service_traits::MD5Sum< ::crazyflie_gazebo::AddCrazyflieRequest> should match 
// service_traits::MD5Sum< ::crazyflie_gazebo::AddCrazyflie > 
template<>
struct MD5Sum< ::crazyflie_gazebo::AddCrazyflieRequest>
{
  static const char* value()
  {
    return MD5Sum< ::crazyflie_gazebo::AddCrazyflie >::value();
  }
  static const char* value(const ::crazyflie_gazebo::AddCrazyflieRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::crazyflie_gazebo::AddCrazyflieRequest> should match 
// service_traits::DataType< ::crazyflie_gazebo::AddCrazyflie > 
template<>
struct DataType< ::crazyflie_gazebo::AddCrazyflieRequest>
{
  static const char* value()
  {
    return DataType< ::crazyflie_gazebo::AddCrazyflie >::value();
  }
  static const char* value(const ::crazyflie_gazebo::AddCrazyflieRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::crazyflie_gazebo::AddCrazyflieResponse> should match 
// service_traits::MD5Sum< ::crazyflie_gazebo::AddCrazyflie > 
template<>
struct MD5Sum< ::crazyflie_gazebo::AddCrazyflieResponse>
{
  static const char* value()
  {
    return MD5Sum< ::crazyflie_gazebo::AddCrazyflie >::value();
  }
  static const char* value(const ::crazyflie_gazebo::AddCrazyflieResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::crazyflie_gazebo::AddCrazyflieResponse> should match 
// service_traits::DataType< ::crazyflie_gazebo::AddCrazyflie > 
template<>
struct DataType< ::crazyflie_gazebo::AddCrazyflieResponse>
{
  static const char* value()
  {
    return DataType< ::crazyflie_gazebo::AddCrazyflie >::value();
  }
  static const char* value(const ::crazyflie_gazebo::AddCrazyflieResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CRAZYFLIE_GAZEBO_MESSAGE_ADDCRAZYFLIE_H
