// Generated by gencpp from file crazyflie_gazebo/GoTo.msg
// DO NOT EDIT!


#ifndef CRAZYFLIE_GAZEBO_MESSAGE_GOTO_H
#define CRAZYFLIE_GAZEBO_MESSAGE_GOTO_H

#include <ros/service_traits.h>


#include <crazyflie_gazebo/GoToRequest.h>
#include <crazyflie_gazebo/GoToResponse.h>


namespace crazyflie_gazebo
{

struct GoTo
{

typedef GoToRequest Request;
typedef GoToResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GoTo
} // namespace crazyflie_gazebo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::crazyflie_gazebo::GoTo > {
  static const char* value()
  {
    return "82856b48a972d6af023d961a655bcf75";
  }

  static const char* value(const ::crazyflie_gazebo::GoTo&) { return value(); }
};

template<>
struct DataType< ::crazyflie_gazebo::GoTo > {
  static const char* value()
  {
    return "crazyflie_gazebo/GoTo";
  }

  static const char* value(const ::crazyflie_gazebo::GoTo&) { return value(); }
};


// service_traits::MD5Sum< ::crazyflie_gazebo::GoToRequest> should match 
// service_traits::MD5Sum< ::crazyflie_gazebo::GoTo > 
template<>
struct MD5Sum< ::crazyflie_gazebo::GoToRequest>
{
  static const char* value()
  {
    return MD5Sum< ::crazyflie_gazebo::GoTo >::value();
  }
  static const char* value(const ::crazyflie_gazebo::GoToRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::crazyflie_gazebo::GoToRequest> should match 
// service_traits::DataType< ::crazyflie_gazebo::GoTo > 
template<>
struct DataType< ::crazyflie_gazebo::GoToRequest>
{
  static const char* value()
  {
    return DataType< ::crazyflie_gazebo::GoTo >::value();
  }
  static const char* value(const ::crazyflie_gazebo::GoToRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::crazyflie_gazebo::GoToResponse> should match 
// service_traits::MD5Sum< ::crazyflie_gazebo::GoTo > 
template<>
struct MD5Sum< ::crazyflie_gazebo::GoToResponse>
{
  static const char* value()
  {
    return MD5Sum< ::crazyflie_gazebo::GoTo >::value();
  }
  static const char* value(const ::crazyflie_gazebo::GoToResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::crazyflie_gazebo::GoToResponse> should match 
// service_traits::DataType< ::crazyflie_gazebo::GoTo > 
template<>
struct DataType< ::crazyflie_gazebo::GoToResponse>
{
  static const char* value()
  {
    return DataType< ::crazyflie_gazebo::GoTo >::value();
  }
  static const char* value(const ::crazyflie_gazebo::GoToResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CRAZYFLIE_GAZEBO_MESSAGE_GOTO_H
