// Generated by gencpp from file crazyflie_gazebo/UpdateParams.msg
// DO NOT EDIT!


#ifndef CRAZYFLIE_GAZEBO_MESSAGE_UPDATEPARAMS_H
#define CRAZYFLIE_GAZEBO_MESSAGE_UPDATEPARAMS_H

#include <ros/service_traits.h>


#include <crazyflie_gazebo/UpdateParamsRequest.h>
#include <crazyflie_gazebo/UpdateParamsResponse.h>


namespace crazyflie_gazebo
{

struct UpdateParams
{

typedef UpdateParamsRequest Request;
typedef UpdateParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UpdateParams
} // namespace crazyflie_gazebo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::crazyflie_gazebo::UpdateParams > {
  static const char* value()
  {
    return "279e0627eb574ffe8968384218434f5f";
  }

  static const char* value(const ::crazyflie_gazebo::UpdateParams&) { return value(); }
};

template<>
struct DataType< ::crazyflie_gazebo::UpdateParams > {
  static const char* value()
  {
    return "crazyflie_gazebo/UpdateParams";
  }

  static const char* value(const ::crazyflie_gazebo::UpdateParams&) { return value(); }
};


// service_traits::MD5Sum< ::crazyflie_gazebo::UpdateParamsRequest> should match 
// service_traits::MD5Sum< ::crazyflie_gazebo::UpdateParams > 
template<>
struct MD5Sum< ::crazyflie_gazebo::UpdateParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::crazyflie_gazebo::UpdateParams >::value();
  }
  static const char* value(const ::crazyflie_gazebo::UpdateParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::crazyflie_gazebo::UpdateParamsRequest> should match 
// service_traits::DataType< ::crazyflie_gazebo::UpdateParams > 
template<>
struct DataType< ::crazyflie_gazebo::UpdateParamsRequest>
{
  static const char* value()
  {
    return DataType< ::crazyflie_gazebo::UpdateParams >::value();
  }
  static const char* value(const ::crazyflie_gazebo::UpdateParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::crazyflie_gazebo::UpdateParamsResponse> should match 
// service_traits::MD5Sum< ::crazyflie_gazebo::UpdateParams > 
template<>
struct MD5Sum< ::crazyflie_gazebo::UpdateParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::crazyflie_gazebo::UpdateParams >::value();
  }
  static const char* value(const ::crazyflie_gazebo::UpdateParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::crazyflie_gazebo::UpdateParamsResponse> should match 
// service_traits::DataType< ::crazyflie_gazebo::UpdateParams > 
template<>
struct DataType< ::crazyflie_gazebo::UpdateParamsResponse>
{
  static const char* value()
  {
    return DataType< ::crazyflie_gazebo::UpdateParams >::value();
  }
  static const char* value(const ::crazyflie_gazebo::UpdateParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CRAZYFLIE_GAZEBO_MESSAGE_UPDATEPARAMS_H
