// Generated by gencpp from file crazyflie_gazebo/UploadTrajectory.msg
// DO NOT EDIT!


#ifndef CRAZYFLIE_GAZEBO_MESSAGE_UPLOADTRAJECTORY_H
#define CRAZYFLIE_GAZEBO_MESSAGE_UPLOADTRAJECTORY_H

#include <ros/service_traits.h>


#include <crazyflie_gazebo/UploadTrajectoryRequest.h>
#include <crazyflie_gazebo/UploadTrajectoryResponse.h>


namespace crazyflie_gazebo
{

struct UploadTrajectory
{

typedef UploadTrajectoryRequest Request;
typedef UploadTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UploadTrajectory
} // namespace crazyflie_gazebo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::crazyflie_gazebo::UploadTrajectory > {
  static const char* value()
  {
    return "becd7733dfdc3d0c93a9064ba651cf17";
  }

  static const char* value(const ::crazyflie_gazebo::UploadTrajectory&) { return value(); }
};

template<>
struct DataType< ::crazyflie_gazebo::UploadTrajectory > {
  static const char* value()
  {
    return "crazyflie_gazebo/UploadTrajectory";
  }

  static const char* value(const ::crazyflie_gazebo::UploadTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::crazyflie_gazebo::UploadTrajectoryRequest> should match 
// service_traits::MD5Sum< ::crazyflie_gazebo::UploadTrajectory > 
template<>
struct MD5Sum< ::crazyflie_gazebo::UploadTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::crazyflie_gazebo::UploadTrajectory >::value();
  }
  static const char* value(const ::crazyflie_gazebo::UploadTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::crazyflie_gazebo::UploadTrajectoryRequest> should match 
// service_traits::DataType< ::crazyflie_gazebo::UploadTrajectory > 
template<>
struct DataType< ::crazyflie_gazebo::UploadTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::crazyflie_gazebo::UploadTrajectory >::value();
  }
  static const char* value(const ::crazyflie_gazebo::UploadTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::crazyflie_gazebo::UploadTrajectoryResponse> should match 
// service_traits::MD5Sum< ::crazyflie_gazebo::UploadTrajectory > 
template<>
struct MD5Sum< ::crazyflie_gazebo::UploadTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::crazyflie_gazebo::UploadTrajectory >::value();
  }
  static const char* value(const ::crazyflie_gazebo::UploadTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::crazyflie_gazebo::UploadTrajectoryResponse> should match 
// service_traits::DataType< ::crazyflie_gazebo::UploadTrajectory > 
template<>
struct DataType< ::crazyflie_gazebo::UploadTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::crazyflie_gazebo::UploadTrajectory >::value();
  }
  static const char* value(const ::crazyflie_gazebo::UploadTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CRAZYFLIE_GAZEBO_MESSAGE_UPLOADTRAJECTORY_H
