#!/usr/bin/env python

import sys
import math
import json
import random

import math
import rospy
import tf2_ros
import tf2_geometry_msgs
from tf.transformations import euler_from_quaternion
from geometry_msgs.msg import PoseStamped
from crazyflie_driver.msg import Position, Hover

idnt = 1
state = 1

def cmd_func(msg):
    global idnt, state
    
    cmd = Hover()
    cmd.header.stamp = rospy.Time.now()
    cmd.header.frame_id = msg.header.frame_id
    cmd.vx = 0
    cmd.vy = 0
    cmd.zDistance = 0.2                        
    pub_cmd.publish(cmd)



rospy.init_node('moveit')
sub_goal = rospy.Subscriber('/move_base_simple/goal', PoseStamped, goal_callback)
pub_cmd  = rospy.Publisher('/cf1/cmd_hover', Hover, queue_size=2)
tf_buf   = tf2_ros.Buffer()
tf_lstn  = tf2_ros.TransformListener(tf_buf)


if __name__ == "__main__":
    global idnt, state

    rospy.spin()