// Generated by gencpp from file crazyflie_gazebo/SetGroupMask.msg
// DO NOT EDIT!


#ifndef CRAZYFLIE_GAZEBO_MESSAGE_SETGROUPMASK_H
#define CRAZYFLIE_GAZEBO_MESSAGE_SETGROUPMASK_H

#include <ros/service_traits.h>


#include <crazyflie_gazebo/SetGroupMaskRequest.h>
#include <crazyflie_gazebo/SetGroupMaskResponse.h>


namespace crazyflie_gazebo
{

struct SetGroupMask
{

typedef SetGroupMaskRequest Request;
typedef SetGroupMaskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGroupMask
} // namespace crazyflie_gazebo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::crazyflie_gazebo::SetGroupMask > {
  static const char* value()
  {
    return "d44d7e9aa94d069ed5834dbd7329e1bb";
  }

  static const char* value(const ::crazyflie_gazebo::SetGroupMask&) { return value(); }
};

template<>
struct DataType< ::crazyflie_gazebo::SetGroupMask > {
  static const char* value()
  {
    return "crazyflie_gazebo/SetGroupMask";
  }

  static const char* value(const ::crazyflie_gazebo::SetGroupMask&) { return value(); }
};


// service_traits::MD5Sum< ::crazyflie_gazebo::SetGroupMaskRequest> should match 
// service_traits::MD5Sum< ::crazyflie_gazebo::SetGroupMask > 
template<>
struct MD5Sum< ::crazyflie_gazebo::SetGroupMaskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::crazyflie_gazebo::SetGroupMask >::value();
  }
  static const char* value(const ::crazyflie_gazebo::SetGroupMaskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::crazyflie_gazebo::SetGroupMaskRequest> should match 
// service_traits::DataType< ::crazyflie_gazebo::SetGroupMask > 
template<>
struct DataType< ::crazyflie_gazebo::SetGroupMaskRequest>
{
  static const char* value()
  {
    return DataType< ::crazyflie_gazebo::SetGroupMask >::value();
  }
  static const char* value(const ::crazyflie_gazebo::SetGroupMaskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::crazyflie_gazebo::SetGroupMaskResponse> should match 
// service_traits::MD5Sum< ::crazyflie_gazebo::SetGroupMask > 
template<>
struct MD5Sum< ::crazyflie_gazebo::SetGroupMaskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::crazyflie_gazebo::SetGroupMask >::value();
  }
  static const char* value(const ::crazyflie_gazebo::SetGroupMaskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::crazyflie_gazebo::SetGroupMaskResponse> should match 
// service_traits::DataType< ::crazyflie_gazebo::SetGroupMask > 
template<>
struct DataType< ::crazyflie_gazebo::SetGroupMaskResponse>
{
  static const char* value()
  {
    return DataType< ::crazyflie_gazebo::SetGroupMask >::value();
  }
  static const char* value(const ::crazyflie_gazebo::SetGroupMaskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CRAZYFLIE_GAZEBO_MESSAGE_SETGROUPMASK_H
